create table Address (id bigint generated by default as identity (start with 1), address varchar(255), city varchar(255), state varchar(255), zip varchar(255), primary key (id))
create table Child (id bigint generated by default as identity (start with 1), balance numeric(19,2), firstName varchar(255), institution varchar(255), lastName varchar(255), state varchar(255), studentId varchar(255), parentId bigint, primary key (id))
create table CreditCard (id bigint generated by default as identity (start with 1), cardNumber varchar(255), ccv varchar(255), expiration varchar(255), name varchar(255), parentId bigint, primary key (id))
create table Parent (id bigint generated by default as identity (start with 1), email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), username varchar(255), primary key (id))
alter table Child add constraint FK_9pin8lcpg1ptchtiuc1ai1gu foreign key (parentId) references Parent
alter table CreditCard add constraint FK_7c6eudcq0c1cih1fdaewyokkw foreign key (parentId) references Parent
